before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: h6bxPdp/oHnBuCm9zsdJloa1Fy4Ay3jYcM+VcyKeE4qlPwfalR96oikQXPBeUaX6xL53D5XcdNNNBgSecrdqcyN+2MRsQh+oMmmuAyzsD0GgF0CK/N59gM2YzJdthLEETblvWB6/OqZi+Khy6MVG13r4DylFJjF+wz/DOd0PAKxWajjJ3/ne62geyUorI55gsTIkkbCB8Ofdsmiepal73ken+cX3aMtuVs9KG75g9/5TV9ybzuEJ0SIQzn1Xz5AO8urq9HwGxJ+measDEjnjnYUTsuiJozrOnqVPKJIn+tedENaNdC8tlV0d9P7BkFFs9I/wKNCopmTPHKSCxz4aUbpfm9GVg0bTUwikKqy/namvF/jZFEAhMLLR5a4MABoIoULr9MMcbfrzkyu2fKUpkv6dZbGoRQTk/fE+V7ia0I5yVHoDSjK+94YLgAu8Bu8Rdu2O/jgi/HoyYK75Cgjakn9f2IRY2EDMPfGdHeftGlgns4p8Z0MUABCQ3vT+FZljFBwVEIg4BbksJVRTOSpc/qJ1CCYOvtXAwr8LxFKIvjVGoYxY+k+GHRlrYPE5OtAkUqCLzMBuvXb+hSJUpsrcMfhEne1B6Sl+Kw1g0y97ZxhkE3cUPP9fEOGsG6L7cl3NrWHa/ObFmjWTb1mBXl5STRJfULq7A1rj+eP/eRBV/jw= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    # - 6
    - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
